package hu.ponte.image_resizer.exception;

public enum ERROR_CODE {
    UNCLASSIFIED_ERROR,
    JSON_PARSE_ERROR,
    ILLEGAL_ARGUMENT_ERROR,
    ILLEGAL_STATE_EXCEPTION,
    ENTITY_OBJECT_NOT_FOUND,
    IMAGE_UPLOAD_FAILED,
    NO_SUCH_ELEMENT,
}
