server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/image_resizer?createDatabaseIfNotExist=true&serverTimezone=UTC&characterEncoding=utf8
    username: postgres
    password: test1234
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost:5432/image_resizer
    user: postgres
    password: test1234
    locations: classpath:db/migration
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      show_sql: false
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  profiles:
    active: windows
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
springdoc:
  api-docs:
    path: /api-docs
#  swagger-ui:
#    path: swagger-ui/index.html
app:
  imagemagick:
    path: C:/Program Files/ImageMagick-7.0.10-Q16/magick.exe
    temp-dir: tmp
  image:
    quality: 92
logging:
  file:
    name: log/image_resizer.log
  level:
    hu.ponte: debug
    org.springframework.web: info
    org.hibernate: error
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
