server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/image_resizer?createDatabaseIfNotExist=true&serverTimezone=UTC&characterEncoding=utf8
    username: postgres
    password: test1234
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

logging:
  file:
    name: log/image_resizer.log
  level:
    hu.ponte: debug
    org.springframework.web: info
    org.hibernate: error
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
