openapi: 3.0.1
info:
  title: Image Resizer APP
  description: This is an image resizer application.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Generated server url
tags:
  - name: Image Operations
    description: API endpoints for image processing
paths:
  /api/images/{id}/resize:
    post:
      tags:
        - Image Operations
      summary: Resize specific image
      operationId: resizeImage
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ResizeRequest"
        required: true
      responses:
        "200":
          description: Image resized successfully
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ImageDTO"
        "404":
          description: Image not found
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ImageDTO"
  /api/images/upload/single:
    post:
      tags:
        - Image Operations
      summary: Upload single image
      operationId: uploadSingleImage
      requestBody:
        content:
          application/json:
            schema:
              required:
                - file
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ImageDTO"
  /api/images/upload/multiple:
    post:
      tags:
        - Image Operations
      summary: Upload multiple images
      operationId: uploadMultipleImages
      requestBody:
        content:
          application/json:
            schema:
              required:
                - files
              type: object
              properties:
                files:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ImageDTO"
  /api/images/{id}/processed:
    get:
      tags:
        - Image Operations
      summary: Download processed image
      operationId: downloadProcessedImage
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  type: string
                  format: byte
  /api/images/{id}/original:
    get:
      tags:
        - Image Operations
      summary: Download original image
      operationId: downloadOriginalImage
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  type: string
                  format: byte
components:
  schemas:
    ResizeRequest:
      type: object
      properties:
        width:
          maximum: 10000
          minimum: 1
          type: integer
          format: int32
        height:
          maximum: 10000
          minimum: 1
          type: integer
          format: int32
    ImageDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        originalName:
          type: string
        contentType:
          type: string
        status:
          type: string
          enum:
            - PENDING
            - PROCESSING
            - COMPLETED
            - FAILED
        errorMessage:
          type: string
        uploadedAt:
          type: string
          format: date-time
        processedAt:
          type: string
          format: date-time
        originalWidth:
          type: integer
          format: int32
        originalHeight:
          type: integer
          format: int32
        newWidth:
          type: integer
          format: int32
        newHeight:
          type: integer
          format: int32
        fileSize:
          type: integer
          format: int64
