CREATE TABLE IF NOT EXISTS images
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    original_file_name VARCHAR(255)                            NOT NULL,
    content_type       VARCHAR(255)                            NOT NULL,
    status             VARCHAR(255)                            NOT NULL,
    error_message      VARCHAR(255),
    uploaded_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    processed_at       TIMESTAMP WITHOUT TIME ZONE,
    original_width     INTEGER,
    original_height    INTEGER,
    new_width          INTEGER,
    new_height         INTEGER,
    file_size          BIGINT,
    original_content   OID                                     NOT NULL,
    processed_content  OID,
    CONSTRAINT pk_images PRIMARY KEY (id)
);